version: '3'

services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: always
    env_file:
      - .env
    networks:
      - 42net

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
      - 42net
    expose:
      - "3306"

  wordpress:
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
    restart: on-failure
    expose:
      - "9000"
    networks:
      - 42net

volumes:
  mariadb:
    driver: local
    driver_opts:
        type: volumes
        o: bind
        device: /home/ajeanne/data/mariadb
  wordpress:
    driver: local
    driver_opts:
        type: volumes
        o: bind
        device: /home/ajeanne/data/wordpress

networks:
  42net:
      driver: bridge
